# Blog
keywords: HTML,CSS,JavaScript,Vue,AngularJS,WebPack,UnderScore,System,Raspberry,Tool,Linux,WordPress,NodeJS,MongoDB,Git,Python
author: Virigl,mrchan3668@gmail.com
description: 间歇性凌云壮志，持续性混吃等死
avatar: /images/favicon.png

# Social Accounts
rss: 6708067855351261
weibo: 1953548815
github: pansy-cx
